### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by Shady-1997** [dj-d/AmazonPriceTracker#8]
Ciao Daniele,  sono Andrea, ti ho scritto via email, ricordi? Puoi aiutarmi a capire a cosa è dovuto l'errore che compare quando digito il comando "py main.py":
Traceback (most recent call last):
  File "C:\Users\andre\Desktop\AmazonPriceTracker-master\AmazonPriceTracker-master\main.py", line 18, in <module>
    logging_service = LoggingService(name=__name__, formatter=None, datefmt=None, file_handler=None)
  File "C:\Users\andre\Desktop\AmazonPriceTracker-master\AmazonPriceTracker-master\src\services\logging_service.py", line 16, in __init__
    self.file_handler = logging.FileHandler(file_handler)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1149, in __init__
    filename = os.fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by dj-d** [comment]
Potresti mostrare l'intero errore, perchè penso che ci manchi un pezzo

**Comment by Shady-1997** [comment]
> 

ciao, l'errore è completo. Pero mi sono dimenticato di dirti che non sono riusciuto a capire cosa fare quando dici di "decommentare".

**Comment by dj-d** [comment]
Controllando il README mi accorgo di non aver aggiornato la path del file da aggiornare. Comunque, dentro src/threads/crawler_thread.py, si deve decommentare la riga 28 e commentare la riga 29, perchè mi dava un errore sulla posizione degli elementi nell'array che non avevo ancora risolto. 
Vedi se facendo questa modifica funziona. Io ti consiglierei di utilizzare il deploy tramite docker perchè è quello che ho testato di più, da linea di comando l'ho provato proco.

**Comment by c0mrade69** [comment]
hello, same error here, even though I uncommented ln28 and commented out ln29. Any help ?

**Comment by dj-d** [comment]
I'm sorry for the problems encountered, some of the packages that are used are deprecated and give problems.
I'm working to solve the problems, but I'm also preparing a new version but I need time due to some commitments

**Comment by c0mrade69** [comment]
thanks for reply master. I was trying to update all packages and accordingly change code, but its too much for me :) will have to wait for you to fix it :) Good luck and looking forward on your updates 🤪
